#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SQL_QUANLYHOCSINH")]
	public partial class SQL_QUANLYHOCSINHDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDIEM(DIEM instance);
    partial void UpdateDIEM(DIEM instance);
    partial void DeleteDIEM(DIEM instance);
    partial void InsertGIAOVIEN(GIAOVIEN instance);
    partial void UpdateGIAOVIEN(GIAOVIEN instance);
    partial void DeleteGIAOVIEN(GIAOVIEN instance);
    partial void InsertHOCKY(HOCKY instance);
    partial void UpdateHOCKY(HOCKY instance);
    partial void DeleteHOCKY(HOCKY instance);
    partial void InsertHOCSINH(HOCSINH instance);
    partial void UpdateHOCSINH(HOCSINH instance);
    partial void DeleteHOCSINH(HOCSINH instance);
    partial void InsertKHOI(KHOI instance);
    partial void UpdateKHOI(KHOI instance);
    partial void DeleteKHOI(KHOI instance);
    partial void InsertLOAIDIEM(LOAIDIEM instance);
    partial void UpdateLOAIDIEM(LOAIDIEM instance);
    partial void DeleteLOAIDIEM(LOAIDIEM instance);
    partial void InsertLOP(LOP instance);
    partial void UpdateLOP(LOP instance);
    partial void DeleteLOP(LOP instance);
    partial void InsertMONHOC(MONHOC instance);
    partial void UpdateMONHOC(MONHOC instance);
    partial void DeleteMONHOC(MONHOC instance);
    partial void InsertNAMHOC(NAMHOC instance);
    partial void UpdateNAMHOC(NAMHOC instance);
    partial void DeleteNAMHOC(NAMHOC instance);
    partial void InsertPHANLOP(PHANLOP instance);
    partial void UpdatePHANLOP(PHANLOP instance);
    partial void DeletePHANLOP(PHANLOP instance);
    #endregion
		
		public SQL_QUANLYHOCSINHDataContext() : 
				base(global::DAO.Properties.Settings.Default.SQL_QUANLYHOCSINHConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public SQL_QUANLYHOCSINHDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQL_QUANLYHOCSINHDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQL_QUANLYHOCSINHDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQL_QUANLYHOCSINHDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DIEM> DIEMs
		{
			get
			{
				return this.GetTable<DIEM>();
			}
		}
		
		public System.Data.Linq.Table<QUIDINH> QUIDINHs
		{
			get
			{
				return this.GetTable<QUIDINH>();
			}
		}
		
		public System.Data.Linq.Table<GIAOVIEN> GIAOVIENs
		{
			get
			{
				return this.GetTable<GIAOVIEN>();
			}
		}
		
		public System.Data.Linq.Table<HOCKY> HOCKies
		{
			get
			{
				return this.GetTable<HOCKY>();
			}
		}
		
		public System.Data.Linq.Table<HOCSINH> HOCSINHs
		{
			get
			{
				return this.GetTable<HOCSINH>();
			}
		}
		
		public System.Data.Linq.Table<KHOI> KHOIs
		{
			get
			{
				return this.GetTable<KHOI>();
			}
		}
		
		public System.Data.Linq.Table<LOAIDIEM> LOAIDIEMs
		{
			get
			{
				return this.GetTable<LOAIDIEM>();
			}
		}
		
		public System.Data.Linq.Table<LOP> LOPs
		{
			get
			{
				return this.GetTable<LOP>();
			}
		}
		
		public System.Data.Linq.Table<MONHOC> MONHOCs
		{
			get
			{
				return this.GetTable<MONHOC>();
			}
		}
		
		public System.Data.Linq.Table<NAMHOC> NAMHOCs
		{
			get
			{
				return this.GetTable<NAMHOC>();
			}
		}
		
		public System.Data.Linq.Table<PHANLOP> PHANLOPs
		{
			get
			{
				return this.GetTable<PHANLOP>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SuaThongtinHocSinh")]
		public int sp_SuaThongtinHocSinh([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> mahs, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string hoten, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(3)")] string gioitinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> ngaysinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string diachi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string tongiao, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string hotencha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string nghenghiepcha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string hotenme, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string nghenghiepme, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(5)")] string malop)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mahs, hoten, gioitinh, ngaysinh, diachi, email, tongiao, hotencha, nghenghiepcha, hotenme, nghenghiepme, malop);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_XoathongtinHocSinh")]
		public int sp_XoathongtinHocSinh([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> mahs)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mahs);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ThemHocSinh")]
		public int sp_ThemHocSinh([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> mahs, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string hoten, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(3)")] string gioitinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> ngaysinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string diachi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string tongiao, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string hotencha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string nghenghiepcha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string hotenme, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string nghenghiepme, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(5)")] string malop, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> manamhoc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(2)")] string makhoilop)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mahs, hoten, gioitinh, ngaysinh, diachi, email, tongiao, hotencha, nghenghiepcha, hotenme, nghenghiepme, malop, manamhoc, makhoilop);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ThongtinHocSinhtheoKhoi")]
		public ISingleResult<sp_ThongtinHocSinhtheoKhoiResult> sp_ThongtinHocSinhtheoKhoi([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(2)")] string makhoi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), makhoi);
			return ((ISingleResult<sp_ThongtinHocSinhtheoKhoiResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ThongtinHocSinhtheoLop")]
		public ISingleResult<sp_ThongtinHocSinhtheoLopResult> sp_ThongtinHocSinhtheoLop([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(5)")] string malop)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), malop);
			return ((ISingleResult<sp_ThongtinHocSinhtheoLopResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIEM")]
	public partial class DIEM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STT;
		
		private System.Nullable<int> _MAHS;
		
		private string _MAMONHOC;
		
		private string _MAHOCKY;
		
		private System.Nullable<int> _MANAMHOC;
		
		private string _MALOP;
		
		private string _MALOAIDIEM;
		
		private System.Nullable<double> _DIEM1;
		
		private EntityRef<HOCKY> _HOCKY;
		
		private EntityRef<HOCSINH> _HOCSINH;
		
		private EntityRef<LOAIDIEM> _LOAIDIEM;
		
		private EntityRef<LOP> _LOP;
		
		private EntityRef<MONHOC> _MONHOC;
		
		private EntityRef<NAMHOC> _NAMHOC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnMAHSChanging(System.Nullable<int> value);
    partial void OnMAHSChanged();
    partial void OnMAMONHOCChanging(string value);
    partial void OnMAMONHOCChanged();
    partial void OnMAHOCKYChanging(string value);
    partial void OnMAHOCKYChanged();
    partial void OnMANAMHOCChanging(System.Nullable<int> value);
    partial void OnMANAMHOCChanged();
    partial void OnMALOPChanging(string value);
    partial void OnMALOPChanged();
    partial void OnMALOAIDIEMChanging(string value);
    partial void OnMALOAIDIEMChanged();
    partial void OnDIEM1Changing(System.Nullable<double> value);
    partial void OnDIEM1Changed();
    #endregion
		
		public DIEM()
		{
			this._HOCKY = default(EntityRef<HOCKY>);
			this._HOCSINH = default(EntityRef<HOCSINH>);
			this._LOAIDIEM = default(EntityRef<LOAIDIEM>);
			this._LOP = default(EntityRef<LOP>);
			this._MONHOC = default(EntityRef<MONHOC>);
			this._NAMHOC = default(EntityRef<NAMHOC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHS", DbType="Int")]
		public System.Nullable<int> MAHS
		{
			get
			{
				return this._MAHS;
			}
			set
			{
				if ((this._MAHS != value))
				{
					if (this._HOCSINH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAHSChanging(value);
					this.SendPropertyChanging();
					this._MAHS = value;
					this.SendPropertyChanged("MAHS");
					this.OnMAHSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMONHOC", DbType="VarChar(10)")]
		public string MAMONHOC
		{
			get
			{
				return this._MAMONHOC;
			}
			set
			{
				if ((this._MAMONHOC != value))
				{
					if (this._MONHOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAMONHOCChanging(value);
					this.SendPropertyChanging();
					this._MAMONHOC = value;
					this.SendPropertyChanged("MAMONHOC");
					this.OnMAMONHOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHOCKY", DbType="Char(2)")]
		public string MAHOCKY
		{
			get
			{
				return this._MAHOCKY;
			}
			set
			{
				if ((this._MAHOCKY != value))
				{
					if (this._HOCKY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAHOCKYChanging(value);
					this.SendPropertyChanging();
					this._MAHOCKY = value;
					this.SendPropertyChanged("MAHOCKY");
					this.OnMAHOCKYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAMHOC", DbType="Int")]
		public System.Nullable<int> MANAMHOC
		{
			get
			{
				return this._MANAMHOC;
			}
			set
			{
				if ((this._MANAMHOC != value))
				{
					if (this._NAMHOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANAMHOCChanging(value);
					this.SendPropertyChanging();
					this._MANAMHOC = value;
					this.SendPropertyChanged("MANAMHOC");
					this.OnMANAMHOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOP", DbType="Char(5)")]
		public string MALOP
		{
			get
			{
				return this._MALOP;
			}
			set
			{
				if ((this._MALOP != value))
				{
					if (this._LOP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOPChanging(value);
					this.SendPropertyChanging();
					this._MALOP = value;
					this.SendPropertyChanged("MALOP");
					this.OnMALOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAIDIEM", DbType="VarChar(7)")]
		public string MALOAIDIEM
		{
			get
			{
				return this._MALOAIDIEM;
			}
			set
			{
				if ((this._MALOAIDIEM != value))
				{
					if (this._LOAIDIEM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAIDIEMChanging(value);
					this.SendPropertyChanging();
					this._MALOAIDIEM = value;
					this.SendPropertyChanged("MALOAIDIEM");
					this.OnMALOAIDIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="DIEM", Storage="_DIEM1", DbType="Float")]
		public System.Nullable<double> DIEM1
		{
			get
			{
				return this._DIEM1;
			}
			set
			{
				if ((this._DIEM1 != value))
				{
					this.OnDIEM1Changing(value);
					this.SendPropertyChanging();
					this._DIEM1 = value;
					this.SendPropertyChanged("DIEM1");
					this.OnDIEM1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOCKY_DIEM", Storage="_HOCKY", ThisKey="MAHOCKY", OtherKey="MAHOCKY", IsForeignKey=true)]
		public HOCKY HOCKY
		{
			get
			{
				return this._HOCKY.Entity;
			}
			set
			{
				HOCKY previousValue = this._HOCKY.Entity;
				if (((previousValue != value) 
							|| (this._HOCKY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOCKY.Entity = null;
						previousValue.DIEMs.Remove(this);
					}
					this._HOCKY.Entity = value;
					if ((value != null))
					{
						value.DIEMs.Add(this);
						this._MAHOCKY = value.MAHOCKY;
					}
					else
					{
						this._MAHOCKY = default(string);
					}
					this.SendPropertyChanged("HOCKY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOCSINH_DIEM", Storage="_HOCSINH", ThisKey="MAHS", OtherKey="MAHS", IsForeignKey=true)]
		public HOCSINH HOCSINH
		{
			get
			{
				return this._HOCSINH.Entity;
			}
			set
			{
				HOCSINH previousValue = this._HOCSINH.Entity;
				if (((previousValue != value) 
							|| (this._HOCSINH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOCSINH.Entity = null;
						previousValue.DIEMs.Remove(this);
					}
					this._HOCSINH.Entity = value;
					if ((value != null))
					{
						value.DIEMs.Add(this);
						this._MAHS = value.MAHS;
					}
					else
					{
						this._MAHS = default(Nullable<int>);
					}
					this.SendPropertyChanged("HOCSINH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIDIEM_DIEM", Storage="_LOAIDIEM", ThisKey="MALOAIDIEM", OtherKey="MALOAIDIEM", IsForeignKey=true)]
		public LOAIDIEM LOAIDIEM
		{
			get
			{
				return this._LOAIDIEM.Entity;
			}
			set
			{
				LOAIDIEM previousValue = this._LOAIDIEM.Entity;
				if (((previousValue != value) 
							|| (this._LOAIDIEM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIDIEM.Entity = null;
						previousValue.DIEMs.Remove(this);
					}
					this._LOAIDIEM.Entity = value;
					if ((value != null))
					{
						value.DIEMs.Add(this);
						this._MALOAIDIEM = value.MALOAIDIEM;
					}
					else
					{
						this._MALOAIDIEM = default(string);
					}
					this.SendPropertyChanged("LOAIDIEM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOP_DIEM", Storage="_LOP", ThisKey="MALOP", OtherKey="MALOP", IsForeignKey=true)]
		public LOP LOP
		{
			get
			{
				return this._LOP.Entity;
			}
			set
			{
				LOP previousValue = this._LOP.Entity;
				if (((previousValue != value) 
							|| (this._LOP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOP.Entity = null;
						previousValue.DIEMs.Remove(this);
					}
					this._LOP.Entity = value;
					if ((value != null))
					{
						value.DIEMs.Add(this);
						this._MALOP = value.MALOP;
					}
					else
					{
						this._MALOP = default(string);
					}
					this.SendPropertyChanged("LOP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MONHOC_DIEM", Storage="_MONHOC", ThisKey="MAMONHOC", OtherKey="MAMONHOC", IsForeignKey=true)]
		public MONHOC MONHOC
		{
			get
			{
				return this._MONHOC.Entity;
			}
			set
			{
				MONHOC previousValue = this._MONHOC.Entity;
				if (((previousValue != value) 
							|| (this._MONHOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MONHOC.Entity = null;
						previousValue.DIEMs.Remove(this);
					}
					this._MONHOC.Entity = value;
					if ((value != null))
					{
						value.DIEMs.Add(this);
						this._MAMONHOC = value.MAMONHOC;
					}
					else
					{
						this._MAMONHOC = default(string);
					}
					this.SendPropertyChanged("MONHOC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NAMHOC_DIEM", Storage="_NAMHOC", ThisKey="MANAMHOC", OtherKey="MANAMHOC", IsForeignKey=true)]
		public NAMHOC NAMHOC
		{
			get
			{
				return this._NAMHOC.Entity;
			}
			set
			{
				NAMHOC previousValue = this._NAMHOC.Entity;
				if (((previousValue != value) 
							|| (this._NAMHOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NAMHOC.Entity = null;
						previousValue.DIEMs.Remove(this);
					}
					this._NAMHOC.Entity = value;
					if ((value != null))
					{
						value.DIEMs.Add(this);
						this._MANAMHOC = value.MANAMHOC;
					}
					else
					{
						this._MANAMHOC = default(Nullable<int>);
					}
					this.SendPropertyChanged("NAMHOC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUIDINH")]
	public partial class QUIDINH
	{
		
		private System.Nullable<int> _TUOITOITHIEU;
		
		private System.Nullable<int> _TUOITOIDA;
		
		private System.Nullable<int> _SISOTOITHIEU;
		
		private System.Nullable<int> _SISOTOIDA;
		
		private System.Nullable<double> _DIEMTOITHIEU;
		
		private System.Nullable<double> _DIEMTOIDA;
		
		public QUIDINH()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUOITOITHIEU", DbType="Int")]
		public System.Nullable<int> TUOITOITHIEU
		{
			get
			{
				return this._TUOITOITHIEU;
			}
			set
			{
				if ((this._TUOITOITHIEU != value))
				{
					this._TUOITOITHIEU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUOITOIDA", DbType="Int")]
		public System.Nullable<int> TUOITOIDA
		{
			get
			{
				return this._TUOITOIDA;
			}
			set
			{
				if ((this._TUOITOIDA != value))
				{
					this._TUOITOIDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SISOTOITHIEU", DbType="Int")]
		public System.Nullable<int> SISOTOITHIEU
		{
			get
			{
				return this._SISOTOITHIEU;
			}
			set
			{
				if ((this._SISOTOITHIEU != value))
				{
					this._SISOTOITHIEU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SISOTOIDA", DbType="Int")]
		public System.Nullable<int> SISOTOIDA
		{
			get
			{
				return this._SISOTOIDA;
			}
			set
			{
				if ((this._SISOTOIDA != value))
				{
					this._SISOTOIDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEMTOITHIEU", DbType="Float")]
		public System.Nullable<double> DIEMTOITHIEU
		{
			get
			{
				return this._DIEMTOITHIEU;
			}
			set
			{
				if ((this._DIEMTOITHIEU != value))
				{
					this._DIEMTOITHIEU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEMTOIDA", DbType="Float")]
		public System.Nullable<double> DIEMTOIDA
		{
			get
			{
				return this._DIEMTOIDA;
			}
			set
			{
				if ((this._DIEMTOIDA != value))
				{
					this._DIEMTOIDA = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIAOVIEN")]
	public partial class GIAOVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAGV;
		
		private string _HOTEN;
		
		private string _GIOITINH;
		
		private string _SODT;
		
		private EntitySet<LOP> _LOPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAGVChanging(string value);
    partial void OnMAGVChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnSODTChanging(string value);
    partial void OnSODTChanged();
    #endregion
		
		public GIAOVIEN()
		{
			this._LOPs = new EntitySet<LOP>(new Action<LOP>(this.attach_LOPs), new Action<LOP>(this.detach_LOPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGV", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAGV
		{
			get
			{
				return this._MAGV;
			}
			set
			{
				if ((this._MAGV != value))
				{
					this.OnMAGVChanging(value);
					this.SendPropertyChanging();
					this._MAGV = value;
					this.SendPropertyChanged("MAGV");
					this.OnMAGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(20)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="Char(3)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODT", DbType="VarChar(11)")]
		public string SODT
		{
			get
			{
				return this._SODT;
			}
			set
			{
				if ((this._SODT != value))
				{
					this.OnSODTChanging(value);
					this.SendPropertyChanging();
					this._SODT = value;
					this.SendPropertyChanged("SODT");
					this.OnSODTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAOVIEN_LOP", Storage="_LOPs", ThisKey="MAGV", OtherKey="MAGVCN")]
		public EntitySet<LOP> LOPs
		{
			get
			{
				return this._LOPs;
			}
			set
			{
				this._LOPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LOPs(LOP entity)
		{
			this.SendPropertyChanging();
			entity.GIAOVIEN = this;
		}
		
		private void detach_LOPs(LOP entity)
		{
			this.SendPropertyChanging();
			entity.GIAOVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOCKY")]
	public partial class HOCKY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHOCKY;
		
		private string _TENHOCKY;
		
		private System.Nullable<short> _HESO;
		
		private EntitySet<DIEM> _DIEMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHOCKYChanging(string value);
    partial void OnMAHOCKYChanged();
    partial void OnTENHOCKYChanging(string value);
    partial void OnTENHOCKYChanged();
    partial void OnHESOChanging(System.Nullable<short> value);
    partial void OnHESOChanged();
    #endregion
		
		public HOCKY()
		{
			this._DIEMs = new EntitySet<DIEM>(new Action<DIEM>(this.attach_DIEMs), new Action<DIEM>(this.detach_DIEMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHOCKY", DbType="Char(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHOCKY
		{
			get
			{
				return this._MAHOCKY;
			}
			set
			{
				if ((this._MAHOCKY != value))
				{
					this.OnMAHOCKYChanging(value);
					this.SendPropertyChanging();
					this._MAHOCKY = value;
					this.SendPropertyChanged("MAHOCKY");
					this.OnMAHOCKYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENHOCKY", DbType="NVarChar(10)")]
		public string TENHOCKY
		{
			get
			{
				return this._TENHOCKY;
			}
			set
			{
				if ((this._TENHOCKY != value))
				{
					this.OnTENHOCKYChanging(value);
					this.SendPropertyChanging();
					this._TENHOCKY = value;
					this.SendPropertyChanged("TENHOCKY");
					this.OnTENHOCKYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HESO", DbType="SmallInt")]
		public System.Nullable<short> HESO
		{
			get
			{
				return this._HESO;
			}
			set
			{
				if ((this._HESO != value))
				{
					this.OnHESOChanging(value);
					this.SendPropertyChanging();
					this._HESO = value;
					this.SendPropertyChanged("HESO");
					this.OnHESOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOCKY_DIEM", Storage="_DIEMs", ThisKey="MAHOCKY", OtherKey="MAHOCKY")]
		public EntitySet<DIEM> DIEMs
		{
			get
			{
				return this._DIEMs;
			}
			set
			{
				this._DIEMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DIEMs(DIEM entity)
		{
			this.SendPropertyChanging();
			entity.HOCKY = this;
		}
		
		private void detach_DIEMs(DIEM entity)
		{
			this.SendPropertyChanging();
			entity.HOCKY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOCSINH")]
	public partial class HOCSINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAHS;
		
		private string _HOTEN;
		
		private string _GIOITINH;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _DIACHI;
		
		private string _EMAIL;
		
		private string _TONGIAO;
		
		private string _HOTENCHAC;
		
		private string _HOTENME;
		
		private string _NGHENGHIEPME;
		
		private string _NGHENGHIEPCHA;
		
		private EntitySet<DIEM> _DIEMs;
		
		private EntitySet<LOP> _LOPs;
		
		private EntitySet<PHANLOP> _PHANLOPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHSChanging(int value);
    partial void OnMAHSChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnTONGIAOChanging(string value);
    partial void OnTONGIAOChanged();
    partial void OnHOTENCHACChanging(string value);
    partial void OnHOTENCHACChanged();
    partial void OnHOTENMEChanging(string value);
    partial void OnHOTENMEChanged();
    partial void OnNGHENGHIEPMEChanging(string value);
    partial void OnNGHENGHIEPMEChanged();
    partial void OnNGHENGHIEPCHAChanging(string value);
    partial void OnNGHENGHIEPCHAChanged();
    #endregion
		
		public HOCSINH()
		{
			this._DIEMs = new EntitySet<DIEM>(new Action<DIEM>(this.attach_DIEMs), new Action<DIEM>(this.detach_DIEMs));
			this._LOPs = new EntitySet<LOP>(new Action<LOP>(this.attach_LOPs), new Action<LOP>(this.detach_LOPs));
			this._PHANLOPs = new EntitySet<PHANLOP>(new Action<PHANLOP>(this.attach_PHANLOPs), new Action<PHANLOP>(this.detach_PHANLOPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHS", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAHS
		{
			get
			{
				return this._MAHS;
			}
			set
			{
				if ((this._MAHS != value))
				{
					this.OnMAHSChanging(value);
					this.SendPropertyChanging();
					this._MAHS = value;
					this.SendPropertyChanged("MAHS");
					this.OnMAHSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="Char(3)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(200)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(30)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGIAO", DbType="VarChar(30)")]
		public string TONGIAO
		{
			get
			{
				return this._TONGIAO;
			}
			set
			{
				if ((this._TONGIAO != value))
				{
					this.OnTONGIAOChanging(value);
					this.SendPropertyChanging();
					this._TONGIAO = value;
					this.SendPropertyChanged("TONGIAO");
					this.OnTONGIAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENCHAC", DbType="VarChar(30)")]
		public string HOTENCHAC
		{
			get
			{
				return this._HOTENCHAC;
			}
			set
			{
				if ((this._HOTENCHAC != value))
				{
					this.OnHOTENCHACChanging(value);
					this.SendPropertyChanging();
					this._HOTENCHAC = value;
					this.SendPropertyChanged("HOTENCHAC");
					this.OnHOTENCHACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENME", DbType="VarChar(30)")]
		public string HOTENME
		{
			get
			{
				return this._HOTENME;
			}
			set
			{
				if ((this._HOTENME != value))
				{
					this.OnHOTENMEChanging(value);
					this.SendPropertyChanging();
					this._HOTENME = value;
					this.SendPropertyChanged("HOTENME");
					this.OnHOTENMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGHENGHIEPME", DbType="VarChar(30)")]
		public string NGHENGHIEPME
		{
			get
			{
				return this._NGHENGHIEPME;
			}
			set
			{
				if ((this._NGHENGHIEPME != value))
				{
					this.OnNGHENGHIEPMEChanging(value);
					this.SendPropertyChanging();
					this._NGHENGHIEPME = value;
					this.SendPropertyChanged("NGHENGHIEPME");
					this.OnNGHENGHIEPMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGHENGHIEPCHA", DbType="VarChar(30)")]
		public string NGHENGHIEPCHA
		{
			get
			{
				return this._NGHENGHIEPCHA;
			}
			set
			{
				if ((this._NGHENGHIEPCHA != value))
				{
					this.OnNGHENGHIEPCHAChanging(value);
					this.SendPropertyChanging();
					this._NGHENGHIEPCHA = value;
					this.SendPropertyChanged("NGHENGHIEPCHA");
					this.OnNGHENGHIEPCHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOCSINH_DIEM", Storage="_DIEMs", ThisKey="MAHS", OtherKey="MAHS")]
		public EntitySet<DIEM> DIEMs
		{
			get
			{
				return this._DIEMs;
			}
			set
			{
				this._DIEMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOCSINH_LOP", Storage="_LOPs", ThisKey="MAHS", OtherKey="MATRGLOP")]
		public EntitySet<LOP> LOPs
		{
			get
			{
				return this._LOPs;
			}
			set
			{
				this._LOPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOCSINH_PHANLOP", Storage="_PHANLOPs", ThisKey="MAHS", OtherKey="MAHS")]
		public EntitySet<PHANLOP> PHANLOPs
		{
			get
			{
				return this._PHANLOPs;
			}
			set
			{
				this._PHANLOPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DIEMs(DIEM entity)
		{
			this.SendPropertyChanging();
			entity.HOCSINH = this;
		}
		
		private void detach_DIEMs(DIEM entity)
		{
			this.SendPropertyChanging();
			entity.HOCSINH = null;
		}
		
		private void attach_LOPs(LOP entity)
		{
			this.SendPropertyChanging();
			entity.HOCSINH = this;
		}
		
		private void detach_LOPs(LOP entity)
		{
			this.SendPropertyChanging();
			entity.HOCSINH = null;
		}
		
		private void attach_PHANLOPs(PHANLOP entity)
		{
			this.SendPropertyChanging();
			entity.HOCSINH = this;
		}
		
		private void detach_PHANLOPs(PHANLOP entity)
		{
			this.SendPropertyChanging();
			entity.HOCSINH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHOI")]
	public partial class KHOI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAKHOILOP;
		
		private string _TENKHOILOP;
		
		private EntitySet<LOP> _LOPs;
		
		private EntitySet<PHANLOP> _PHANLOPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKHOILOPChanging(string value);
    partial void OnMAKHOILOPChanged();
    partial void OnTENKHOILOPChanging(string value);
    partial void OnTENKHOILOPChanged();
    #endregion
		
		public KHOI()
		{
			this._LOPs = new EntitySet<LOP>(new Action<LOP>(this.attach_LOPs), new Action<LOP>(this.detach_LOPs));
			this._PHANLOPs = new EntitySet<PHANLOP>(new Action<PHANLOP>(this.attach_PHANLOPs), new Action<PHANLOP>(this.detach_PHANLOPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHOILOP", DbType="Char(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAKHOILOP
		{
			get
			{
				return this._MAKHOILOP;
			}
			set
			{
				if ((this._MAKHOILOP != value))
				{
					this.OnMAKHOILOPChanging(value);
					this.SendPropertyChanging();
					this._MAKHOILOP = value;
					this.SendPropertyChanged("MAKHOILOP");
					this.OnMAKHOILOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKHOILOP", DbType="VarChar(20)")]
		public string TENKHOILOP
		{
			get
			{
				return this._TENKHOILOP;
			}
			set
			{
				if ((this._TENKHOILOP != value))
				{
					this.OnTENKHOILOPChanging(value);
					this.SendPropertyChanging();
					this._TENKHOILOP = value;
					this.SendPropertyChanged("TENKHOILOP");
					this.OnTENKHOILOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOI_LOP", Storage="_LOPs", ThisKey="MAKHOILOP", OtherKey="MAKHOILOP")]
		public EntitySet<LOP> LOPs
		{
			get
			{
				return this._LOPs;
			}
			set
			{
				this._LOPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOI_PHANLOP", Storage="_PHANLOPs", ThisKey="MAKHOILOP", OtherKey="MAKHOILOP")]
		public EntitySet<PHANLOP> PHANLOPs
		{
			get
			{
				return this._PHANLOPs;
			}
			set
			{
				this._PHANLOPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LOPs(LOP entity)
		{
			this.SendPropertyChanging();
			entity.KHOI = this;
		}
		
		private void detach_LOPs(LOP entity)
		{
			this.SendPropertyChanging();
			entity.KHOI = null;
		}
		
		private void attach_PHANLOPs(PHANLOP entity)
		{
			this.SendPropertyChanging();
			entity.KHOI = this;
		}
		
		private void detach_PHANLOPs(PHANLOP entity)
		{
			this.SendPropertyChanging();
			entity.KHOI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIDIEM")]
	public partial class LOAIDIEM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MALOAIDIEM;
		
		private string _TENLOAIDIEM;
		
		private System.Nullable<short> _HESO;
		
		private EntitySet<DIEM> _DIEMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOAIDIEMChanging(string value);
    partial void OnMALOAIDIEMChanged();
    partial void OnTENLOAIDIEMChanging(string value);
    partial void OnTENLOAIDIEMChanged();
    partial void OnHESOChanging(System.Nullable<short> value);
    partial void OnHESOChanged();
    #endregion
		
		public LOAIDIEM()
		{
			this._DIEMs = new EntitySet<DIEM>(new Action<DIEM>(this.attach_DIEMs), new Action<DIEM>(this.detach_DIEMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAIDIEM", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALOAIDIEM
		{
			get
			{
				return this._MALOAIDIEM;
			}
			set
			{
				if ((this._MALOAIDIEM != value))
				{
					this.OnMALOAIDIEMChanging(value);
					this.SendPropertyChanging();
					this._MALOAIDIEM = value;
					this.SendPropertyChanged("MALOAIDIEM");
					this.OnMALOAIDIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAIDIEM", DbType="NVarChar(10)")]
		public string TENLOAIDIEM
		{
			get
			{
				return this._TENLOAIDIEM;
			}
			set
			{
				if ((this._TENLOAIDIEM != value))
				{
					this.OnTENLOAIDIEMChanging(value);
					this.SendPropertyChanging();
					this._TENLOAIDIEM = value;
					this.SendPropertyChanged("TENLOAIDIEM");
					this.OnTENLOAIDIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HESO", DbType="SmallInt")]
		public System.Nullable<short> HESO
		{
			get
			{
				return this._HESO;
			}
			set
			{
				if ((this._HESO != value))
				{
					this.OnHESOChanging(value);
					this.SendPropertyChanging();
					this._HESO = value;
					this.SendPropertyChanged("HESO");
					this.OnHESOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIDIEM_DIEM", Storage="_DIEMs", ThisKey="MALOAIDIEM", OtherKey="MALOAIDIEM")]
		public EntitySet<DIEM> DIEMs
		{
			get
			{
				return this._DIEMs;
			}
			set
			{
				this._DIEMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DIEMs(DIEM entity)
		{
			this.SendPropertyChanging();
			entity.LOAIDIEM = this;
		}
		
		private void detach_DIEMs(DIEM entity)
		{
			this.SendPropertyChanging();
			entity.LOAIDIEM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOP")]
	public partial class LOP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MALOP;
		
		private string _TENLOP;
		
		private System.Nullable<int> _SISO;
		
		private string _MAKHOILOP;
		
		private System.Nullable<int> _MATRGLOP;
		
		private string _MAGVCN;
		
		private EntitySet<DIEM> _DIEMs;
		
		private EntitySet<PHANLOP> _PHANLOPs;
		
		private EntityRef<GIAOVIEN> _GIAOVIEN;
		
		private EntityRef<KHOI> _KHOI;
		
		private EntityRef<HOCSINH> _HOCSINH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOPChanging(string value);
    partial void OnMALOPChanged();
    partial void OnTENLOPChanging(string value);
    partial void OnTENLOPChanged();
    partial void OnSISOChanging(System.Nullable<int> value);
    partial void OnSISOChanged();
    partial void OnMAKHOILOPChanging(string value);
    partial void OnMAKHOILOPChanged();
    partial void OnMATRGLOPChanging(System.Nullable<int> value);
    partial void OnMATRGLOPChanged();
    partial void OnMAGVCNChanging(string value);
    partial void OnMAGVCNChanged();
    #endregion
		
		public LOP()
		{
			this._DIEMs = new EntitySet<DIEM>(new Action<DIEM>(this.attach_DIEMs), new Action<DIEM>(this.detach_DIEMs));
			this._PHANLOPs = new EntitySet<PHANLOP>(new Action<PHANLOP>(this.attach_PHANLOPs), new Action<PHANLOP>(this.detach_PHANLOPs));
			this._GIAOVIEN = default(EntityRef<GIAOVIEN>);
			this._KHOI = default(EntityRef<KHOI>);
			this._HOCSINH = default(EntityRef<HOCSINH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOP", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALOP
		{
			get
			{
				return this._MALOP;
			}
			set
			{
				if ((this._MALOP != value))
				{
					this.OnMALOPChanging(value);
					this.SendPropertyChanging();
					this._MALOP = value;
					this.SendPropertyChanged("MALOP");
					this.OnMALOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOP", DbType="VarChar(20)")]
		public string TENLOP
		{
			get
			{
				return this._TENLOP;
			}
			set
			{
				if ((this._TENLOP != value))
				{
					this.OnTENLOPChanging(value);
					this.SendPropertyChanging();
					this._TENLOP = value;
					this.SendPropertyChanged("TENLOP");
					this.OnTENLOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SISO", DbType="Int")]
		public System.Nullable<int> SISO
		{
			get
			{
				return this._SISO;
			}
			set
			{
				if ((this._SISO != value))
				{
					this.OnSISOChanging(value);
					this.SendPropertyChanging();
					this._SISO = value;
					this.SendPropertyChanged("SISO");
					this.OnSISOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHOILOP", DbType="Char(2)")]
		public string MAKHOILOP
		{
			get
			{
				return this._MAKHOILOP;
			}
			set
			{
				if ((this._MAKHOILOP != value))
				{
					if (this._KHOI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHOILOPChanging(value);
					this.SendPropertyChanging();
					this._MAKHOILOP = value;
					this.SendPropertyChanged("MAKHOILOP");
					this.OnMAKHOILOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATRGLOP", DbType="Int")]
		public System.Nullable<int> MATRGLOP
		{
			get
			{
				return this._MATRGLOP;
			}
			set
			{
				if ((this._MATRGLOP != value))
				{
					if (this._HOCSINH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATRGLOPChanging(value);
					this.SendPropertyChanging();
					this._MATRGLOP = value;
					this.SendPropertyChanged("MATRGLOP");
					this.OnMATRGLOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGVCN", DbType="Char(4)")]
		public string MAGVCN
		{
			get
			{
				return this._MAGVCN;
			}
			set
			{
				if ((this._MAGVCN != value))
				{
					if (this._GIAOVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAGVCNChanging(value);
					this.SendPropertyChanging();
					this._MAGVCN = value;
					this.SendPropertyChanged("MAGVCN");
					this.OnMAGVCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOP_DIEM", Storage="_DIEMs", ThisKey="MALOP", OtherKey="MALOP")]
		public EntitySet<DIEM> DIEMs
		{
			get
			{
				return this._DIEMs;
			}
			set
			{
				this._DIEMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOP_PHANLOP", Storage="_PHANLOPs", ThisKey="MALOP", OtherKey="MALOP")]
		public EntitySet<PHANLOP> PHANLOPs
		{
			get
			{
				return this._PHANLOPs;
			}
			set
			{
				this._PHANLOPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAOVIEN_LOP", Storage="_GIAOVIEN", ThisKey="MAGVCN", OtherKey="MAGV", IsForeignKey=true)]
		public GIAOVIEN GIAOVIEN
		{
			get
			{
				return this._GIAOVIEN.Entity;
			}
			set
			{
				GIAOVIEN previousValue = this._GIAOVIEN.Entity;
				if (((previousValue != value) 
							|| (this._GIAOVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIAOVIEN.Entity = null;
						previousValue.LOPs.Remove(this);
					}
					this._GIAOVIEN.Entity = value;
					if ((value != null))
					{
						value.LOPs.Add(this);
						this._MAGVCN = value.MAGV;
					}
					else
					{
						this._MAGVCN = default(string);
					}
					this.SendPropertyChanged("GIAOVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOI_LOP", Storage="_KHOI", ThisKey="MAKHOILOP", OtherKey="MAKHOILOP", IsForeignKey=true)]
		public KHOI KHOI
		{
			get
			{
				return this._KHOI.Entity;
			}
			set
			{
				KHOI previousValue = this._KHOI.Entity;
				if (((previousValue != value) 
							|| (this._KHOI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHOI.Entity = null;
						previousValue.LOPs.Remove(this);
					}
					this._KHOI.Entity = value;
					if ((value != null))
					{
						value.LOPs.Add(this);
						this._MAKHOILOP = value.MAKHOILOP;
					}
					else
					{
						this._MAKHOILOP = default(string);
					}
					this.SendPropertyChanged("KHOI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOCSINH_LOP", Storage="_HOCSINH", ThisKey="MATRGLOP", OtherKey="MAHS", IsForeignKey=true)]
		public HOCSINH HOCSINH
		{
			get
			{
				return this._HOCSINH.Entity;
			}
			set
			{
				HOCSINH previousValue = this._HOCSINH.Entity;
				if (((previousValue != value) 
							|| (this._HOCSINH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOCSINH.Entity = null;
						previousValue.LOPs.Remove(this);
					}
					this._HOCSINH.Entity = value;
					if ((value != null))
					{
						value.LOPs.Add(this);
						this._MATRGLOP = value.MAHS;
					}
					else
					{
						this._MATRGLOP = default(Nullable<int>);
					}
					this.SendPropertyChanged("HOCSINH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DIEMs(DIEM entity)
		{
			this.SendPropertyChanging();
			entity.LOP = this;
		}
		
		private void detach_DIEMs(DIEM entity)
		{
			this.SendPropertyChanging();
			entity.LOP = null;
		}
		
		private void attach_PHANLOPs(PHANLOP entity)
		{
			this.SendPropertyChanging();
			entity.LOP = this;
		}
		
		private void detach_PHANLOPs(PHANLOP entity)
		{
			this.SendPropertyChanging();
			entity.LOP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MONHOC")]
	public partial class MONHOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAMONHOC;
		
		private string _TENMONHOC;
		
		private EntitySet<DIEM> _DIEMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAMONHOCChanging(string value);
    partial void OnMAMONHOCChanged();
    partial void OnTENMONHOCChanging(string value);
    partial void OnTENMONHOCChanged();
    #endregion
		
		public MONHOC()
		{
			this._DIEMs = new EntitySet<DIEM>(new Action<DIEM>(this.attach_DIEMs), new Action<DIEM>(this.detach_DIEMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMONHOC", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAMONHOC
		{
			get
			{
				return this._MAMONHOC;
			}
			set
			{
				if ((this._MAMONHOC != value))
				{
					this.OnMAMONHOCChanging(value);
					this.SendPropertyChanging();
					this._MAMONHOC = value;
					this.SendPropertyChanged("MAMONHOC");
					this.OnMAMONHOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENMONHOC", DbType="NVarChar(30)")]
		public string TENMONHOC
		{
			get
			{
				return this._TENMONHOC;
			}
			set
			{
				if ((this._TENMONHOC != value))
				{
					this.OnTENMONHOCChanging(value);
					this.SendPropertyChanging();
					this._TENMONHOC = value;
					this.SendPropertyChanged("TENMONHOC");
					this.OnTENMONHOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MONHOC_DIEM", Storage="_DIEMs", ThisKey="MAMONHOC", OtherKey="MAMONHOC")]
		public EntitySet<DIEM> DIEMs
		{
			get
			{
				return this._DIEMs;
			}
			set
			{
				this._DIEMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DIEMs(DIEM entity)
		{
			this.SendPropertyChanging();
			entity.MONHOC = this;
		}
		
		private void detach_DIEMs(DIEM entity)
		{
			this.SendPropertyChanging();
			entity.MONHOC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NAMHOC")]
	public partial class NAMHOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MANAMHOC;
		
		private string _TENNAMHOC;
		
		private EntitySet<DIEM> _DIEMs;
		
		private EntitySet<PHANLOP> _PHANLOPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANAMHOCChanging(int value);
    partial void OnMANAMHOCChanged();
    partial void OnTENNAMHOCChanging(string value);
    partial void OnTENNAMHOCChanged();
    #endregion
		
		public NAMHOC()
		{
			this._DIEMs = new EntitySet<DIEM>(new Action<DIEM>(this.attach_DIEMs), new Action<DIEM>(this.detach_DIEMs));
			this._PHANLOPs = new EntitySet<PHANLOP>(new Action<PHANLOP>(this.attach_PHANLOPs), new Action<PHANLOP>(this.detach_PHANLOPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAMHOC", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MANAMHOC
		{
			get
			{
				return this._MANAMHOC;
			}
			set
			{
				if ((this._MANAMHOC != value))
				{
					this.OnMANAMHOCChanging(value);
					this.SendPropertyChanging();
					this._MANAMHOC = value;
					this.SendPropertyChanged("MANAMHOC");
					this.OnMANAMHOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNAMHOC", DbType="VarChar(20)")]
		public string TENNAMHOC
		{
			get
			{
				return this._TENNAMHOC;
			}
			set
			{
				if ((this._TENNAMHOC != value))
				{
					this.OnTENNAMHOCChanging(value);
					this.SendPropertyChanging();
					this._TENNAMHOC = value;
					this.SendPropertyChanged("TENNAMHOC");
					this.OnTENNAMHOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NAMHOC_DIEM", Storage="_DIEMs", ThisKey="MANAMHOC", OtherKey="MANAMHOC")]
		public EntitySet<DIEM> DIEMs
		{
			get
			{
				return this._DIEMs;
			}
			set
			{
				this._DIEMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NAMHOC_PHANLOP", Storage="_PHANLOPs", ThisKey="MANAMHOC", OtherKey="MANAMHOC")]
		public EntitySet<PHANLOP> PHANLOPs
		{
			get
			{
				return this._PHANLOPs;
			}
			set
			{
				this._PHANLOPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DIEMs(DIEM entity)
		{
			this.SendPropertyChanging();
			entity.NAMHOC = this;
		}
		
		private void detach_DIEMs(DIEM entity)
		{
			this.SendPropertyChanging();
			entity.NAMHOC = null;
		}
		
		private void attach_PHANLOPs(PHANLOP entity)
		{
			this.SendPropertyChanging();
			entity.NAMHOC = this;
		}
		
		private void detach_PHANLOPs(PHANLOP entity)
		{
			this.SendPropertyChanging();
			entity.NAMHOC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHANLOP")]
	public partial class PHANLOP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAHS;
		
		private string _MALOP;
		
		private int _MANAMHOC;
		
		private string _MAKHOILOP;
		
		private EntityRef<HOCSINH> _HOCSINH;
		
		private EntityRef<KHOI> _KHOI;
		
		private EntityRef<LOP> _LOP;
		
		private EntityRef<NAMHOC> _NAMHOC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHSChanging(int value);
    partial void OnMAHSChanged();
    partial void OnMALOPChanging(string value);
    partial void OnMALOPChanged();
    partial void OnMANAMHOCChanging(int value);
    partial void OnMANAMHOCChanged();
    partial void OnMAKHOILOPChanging(string value);
    partial void OnMAKHOILOPChanged();
    #endregion
		
		public PHANLOP()
		{
			this._HOCSINH = default(EntityRef<HOCSINH>);
			this._KHOI = default(EntityRef<KHOI>);
			this._LOP = default(EntityRef<LOP>);
			this._NAMHOC = default(EntityRef<NAMHOC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHS", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAHS
		{
			get
			{
				return this._MAHS;
			}
			set
			{
				if ((this._MAHS != value))
				{
					if (this._HOCSINH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAHSChanging(value);
					this.SendPropertyChanging();
					this._MAHS = value;
					this.SendPropertyChanged("MAHS");
					this.OnMAHSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOP", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALOP
		{
			get
			{
				return this._MALOP;
			}
			set
			{
				if ((this._MALOP != value))
				{
					if (this._LOP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOPChanging(value);
					this.SendPropertyChanging();
					this._MALOP = value;
					this.SendPropertyChanged("MALOP");
					this.OnMALOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAMHOC", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MANAMHOC
		{
			get
			{
				return this._MANAMHOC;
			}
			set
			{
				if ((this._MANAMHOC != value))
				{
					if (this._NAMHOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANAMHOCChanging(value);
					this.SendPropertyChanging();
					this._MANAMHOC = value;
					this.SendPropertyChanged("MANAMHOC");
					this.OnMANAMHOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHOILOP", DbType="Char(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAKHOILOP
		{
			get
			{
				return this._MAKHOILOP;
			}
			set
			{
				if ((this._MAKHOILOP != value))
				{
					if (this._KHOI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHOILOPChanging(value);
					this.SendPropertyChanging();
					this._MAKHOILOP = value;
					this.SendPropertyChanged("MAKHOILOP");
					this.OnMAKHOILOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOCSINH_PHANLOP", Storage="_HOCSINH", ThisKey="MAHS", OtherKey="MAHS", IsForeignKey=true)]
		public HOCSINH HOCSINH
		{
			get
			{
				return this._HOCSINH.Entity;
			}
			set
			{
				HOCSINH previousValue = this._HOCSINH.Entity;
				if (((previousValue != value) 
							|| (this._HOCSINH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOCSINH.Entity = null;
						previousValue.PHANLOPs.Remove(this);
					}
					this._HOCSINH.Entity = value;
					if ((value != null))
					{
						value.PHANLOPs.Add(this);
						this._MAHS = value.MAHS;
					}
					else
					{
						this._MAHS = default(int);
					}
					this.SendPropertyChanged("HOCSINH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOI_PHANLOP", Storage="_KHOI", ThisKey="MAKHOILOP", OtherKey="MAKHOILOP", IsForeignKey=true)]
		public KHOI KHOI
		{
			get
			{
				return this._KHOI.Entity;
			}
			set
			{
				KHOI previousValue = this._KHOI.Entity;
				if (((previousValue != value) 
							|| (this._KHOI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHOI.Entity = null;
						previousValue.PHANLOPs.Remove(this);
					}
					this._KHOI.Entity = value;
					if ((value != null))
					{
						value.PHANLOPs.Add(this);
						this._MAKHOILOP = value.MAKHOILOP;
					}
					else
					{
						this._MAKHOILOP = default(string);
					}
					this.SendPropertyChanged("KHOI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOP_PHANLOP", Storage="_LOP", ThisKey="MALOP", OtherKey="MALOP", IsForeignKey=true)]
		public LOP LOP
		{
			get
			{
				return this._LOP.Entity;
			}
			set
			{
				LOP previousValue = this._LOP.Entity;
				if (((previousValue != value) 
							|| (this._LOP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOP.Entity = null;
						previousValue.PHANLOPs.Remove(this);
					}
					this._LOP.Entity = value;
					if ((value != null))
					{
						value.PHANLOPs.Add(this);
						this._MALOP = value.MALOP;
					}
					else
					{
						this._MALOP = default(string);
					}
					this.SendPropertyChanged("LOP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NAMHOC_PHANLOP", Storage="_NAMHOC", ThisKey="MANAMHOC", OtherKey="MANAMHOC", IsForeignKey=true)]
		public NAMHOC NAMHOC
		{
			get
			{
				return this._NAMHOC.Entity;
			}
			set
			{
				NAMHOC previousValue = this._NAMHOC.Entity;
				if (((previousValue != value) 
							|| (this._NAMHOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NAMHOC.Entity = null;
						previousValue.PHANLOPs.Remove(this);
					}
					this._NAMHOC.Entity = value;
					if ((value != null))
					{
						value.PHANLOPs.Add(this);
						this._MANAMHOC = value.MANAMHOC;
					}
					else
					{
						this._MANAMHOC = default(int);
					}
					this.SendPropertyChanged("NAMHOC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_ThongtinHocSinhtheoKhoiResult
	{
		
		private int _MAHS;
		
		private string _HOTEN;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _GIOITINH;
		
		private string _DIACHI;
		
		private string _TONGIAO;
		
		private string _EMAIL;
		
		private string _HOTENCHAC;
		
		private string _NGHENGHIEPCHA;
		
		private string _HOTENME;
		
		private string _NGHENGHIEPME;
		
		private string _MAKHOILOP;
		
		private string _MALOP;
		
		public sp_ThongtinHocSinhtheoKhoiResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHS", DbType="Int NOT NULL")]
		public int MAHS
		{
			get
			{
				return this._MAHS;
			}
			set
			{
				if ((this._MAHS != value))
				{
					this._MAHS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this._HOTEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this._NGAYSINH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="Char(3)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this._GIOITINH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(200)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this._DIACHI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGIAO", DbType="VarChar(30)")]
		public string TONGIAO
		{
			get
			{
				return this._TONGIAO;
			}
			set
			{
				if ((this._TONGIAO != value))
				{
					this._TONGIAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(30)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENCHAC", DbType="VarChar(30)")]
		public string HOTENCHAC
		{
			get
			{
				return this._HOTENCHAC;
			}
			set
			{
				if ((this._HOTENCHAC != value))
				{
					this._HOTENCHAC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGHENGHIEPCHA", DbType="VarChar(30)")]
		public string NGHENGHIEPCHA
		{
			get
			{
				return this._NGHENGHIEPCHA;
			}
			set
			{
				if ((this._NGHENGHIEPCHA != value))
				{
					this._NGHENGHIEPCHA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENME", DbType="VarChar(30)")]
		public string HOTENME
		{
			get
			{
				return this._HOTENME;
			}
			set
			{
				if ((this._HOTENME != value))
				{
					this._HOTENME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGHENGHIEPME", DbType="VarChar(30)")]
		public string NGHENGHIEPME
		{
			get
			{
				return this._NGHENGHIEPME;
			}
			set
			{
				if ((this._NGHENGHIEPME != value))
				{
					this._NGHENGHIEPME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHOILOP", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MAKHOILOP
		{
			get
			{
				return this._MAKHOILOP;
			}
			set
			{
				if ((this._MAKHOILOP != value))
				{
					this._MAKHOILOP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOP", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string MALOP
		{
			get
			{
				return this._MALOP;
			}
			set
			{
				if ((this._MALOP != value))
				{
					this._MALOP = value;
				}
			}
		}
	}
	
	public partial class sp_ThongtinHocSinhtheoLopResult
	{
		
		private int _MAHS;
		
		private string _HOTEN;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _GIOITINH;
		
		private string _DIACHI;
		
		private string _TONGIAO;
		
		private string _EMAIL;
		
		private string _HOTENCHAC;
		
		private string _NGHENGHIEPCHA;
		
		private string _HOTENME;
		
		private string _NGHENGHIEPME;
		
		private string _MAKHOILOP;
		
		private string _MALOP;
		
		public sp_ThongtinHocSinhtheoLopResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHS", DbType="Int NOT NULL")]
		public int MAHS
		{
			get
			{
				return this._MAHS;
			}
			set
			{
				if ((this._MAHS != value))
				{
					this._MAHS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this._HOTEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this._NGAYSINH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="Char(3)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this._GIOITINH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(200)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this._DIACHI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGIAO", DbType="VarChar(30)")]
		public string TONGIAO
		{
			get
			{
				return this._TONGIAO;
			}
			set
			{
				if ((this._TONGIAO != value))
				{
					this._TONGIAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(30)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENCHAC", DbType="VarChar(30)")]
		public string HOTENCHAC
		{
			get
			{
				return this._HOTENCHAC;
			}
			set
			{
				if ((this._HOTENCHAC != value))
				{
					this._HOTENCHAC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGHENGHIEPCHA", DbType="VarChar(30)")]
		public string NGHENGHIEPCHA
		{
			get
			{
				return this._NGHENGHIEPCHA;
			}
			set
			{
				if ((this._NGHENGHIEPCHA != value))
				{
					this._NGHENGHIEPCHA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENME", DbType="VarChar(30)")]
		public string HOTENME
		{
			get
			{
				return this._HOTENME;
			}
			set
			{
				if ((this._HOTENME != value))
				{
					this._HOTENME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGHENGHIEPME", DbType="VarChar(30)")]
		public string NGHENGHIEPME
		{
			get
			{
				return this._NGHENGHIEPME;
			}
			set
			{
				if ((this._NGHENGHIEPME != value))
				{
					this._NGHENGHIEPME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHOILOP", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MAKHOILOP
		{
			get
			{
				return this._MAKHOILOP;
			}
			set
			{
				if ((this._MAKHOILOP != value))
				{
					this._MAKHOILOP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOP", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string MALOP
		{
			get
			{
				return this._MALOP;
			}
			set
			{
				if ((this._MALOP != value))
				{
					this._MALOP = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
